version: '3'

services:
  app:
    build: .
    ports:
      - "8083:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret

  db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=test
